### PR TITLE
[macOS] Add .NET 9.0 environment to all images

### PR DESCRIPTION
**Pull request by erik-bershel**
# Description

Add new .NET platform version to the macOS runners.

#### Related issue:

https://github.com/actions/runner-images/issues/10973

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by michal-zatloukal — APPROVED** [review]

**Review by sarathrajsrinivasan — APPROVED** [review]

**Comment by erik-bershel** [comment]
Let's hold our horses with this update for now due to the possible issues with the new version of the platform.

**Comment by michal-zatloukal** [comment]
@erik-bershel What platform?

**Comment by erik-bershel** [comment]
.NET 9.0

**Comment by michal-zatloukal** [comment]
What is the issue with .NET 9? It's already released, what is the reason why it's not on the runners?

**Comment by michal-zatloukal** [comment]
@erik-bershel what is the issue with .NET 9 on runners?

**Pull request closed without merging**
