### PR TITLE
Updates .NET SDK

### PR DESCRIPTION
**Pull request by DaleMckeown**
# Description
Updates the .NET framework to include .NET 9.

#### Related issue:
Fixes https://github.com/actions/runner-images/issues/10964

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by Kichura — APPROVED** [review]

**Review by michal-zatloukal — APPROVED** [review]

**Review by atalavera-imi — APPROVED** [review]

**Comment by sdcb** [comment]
come on, let's go!

**Comment by a1-jesper** [comment]
When should we expect this to be completed (at least on Ubuntu images)?

**Comment by frankgalindo-briteris** [comment]
This PR would be very helpful as we are migrating to .NET 9. The agent's inability to build is the most challenging part of the process.

**Comment by michal-zatloukal** [comment]
@frankgalindo-briteris you can install .net 9 manually via dedicated github action to mitigate this

**Comment by Kakaranish** [comment]
When this PR is going to be merge?

**Comment by vidyasagarnimmagaddi** [comment]
Hi @DaleMckeown 
The installation of .Net in Windows is done under [10976](https://github.com/actions/runner-images/pull/10976) ,Further we will add .Net for ubuntu later. Thanks for  your contribution.

**Pull request closed without merging**
