### PR TITLE
[Windows] Cleans telemetry and logs from az

### PR DESCRIPTION
**Pull request by jessehouwing**
Running the cleanup post-tests and software inventory, as these generate more logs and more telemetry

Based on the same fixes made on ubuntu.

# Description
New tool, Bug fixing, or Improvement?
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
**For new tools, please provide total size and installation time.**

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by jessehouwing** [comment]
Tried building the image, but it fails installing Visual Studio 2022, which was untouched by my changes:

```
    azure-arm.image: Downloading package from: https://aka.ms/vs/17/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
    azure-arm.image: Package downloaded successfully in 0.45 seconds
    azure-arm.image: Signature thumbprint do not match expected.
```

**Review by vpolikarpov-akvelon — APPROVED** [review]

**Comment by mikhailkoliada** [comment]
@jessehouwing please rebase :)

**Comment by jessehouwing** [comment]
@mikhailkoliada 👍

**Comment by mikhailkoliada** [comment]
@jessehouwing rebase 1 more time please

**Comment by KimTEriksson** [comment]
@mikhailkoliada Can you rerun the pipeline as it failed on "Timeout waiting for machine to restart".
We currently have the same issue with the signature failing

**Review by mikhailkoliada — APPROVED** [review]

**Comment by jessehouwing** [comment]
Thanks @mikhailkoliada!

**Pull request merged**
