### PR TITLE
[macOS] add README file for M1 runner

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description

Add arm64 readme

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by Alexey-Ayupov — APPROVED** [review]

**Comment by andreasabel** [comment]
Atm, they are not listed in the toplevel README, but I don't know whether this is by intention or oversight.

**Comment by jpsim** [comment]
Instructions are now in the release blog post: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

> To try the new Apple silicon macOS larger runner, update the `runs-on:` key in your GitHub Actions YAML workflow YAML file to target `macos-latest-xlarge` or `macos-13-xlarge`.

**Comment by Saadnajmi** [comment]
Will these come to Azure Devops as well, or only Github Actions for now?

**Comment by thewtex** [comment]
> To try the new Apple silicon macOS larger runner, update the runs-on: key in your GitHub Actions YAML workflow YAML file to target macos-latest-xlarge or macos-13-xlarge.

I tried both `macos-latest-xlarge` and `macos-13-xlarge` here: https://github.com/spatial-image/multiscale-spatial-image/pull/84, but it only results in *Job failed*?

**Comment by Lawere** [comment]
- - @

**Pull request merged**
