### PR TITLE
[Ubuntu] install ODBC before Microsoft repo

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description

Looks like there is a version conflict.

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by rcoup** [comment]
Relates to https://github.com/microsoft/linux-package-repositories/issues/39

**Review by maxim-lobanov — APPROVED** [review]

**Pull request merged**
