### PR TITLE
[Ubuntu] Update Shell Script to Verify Azure CLI Availability

### PR DESCRIPTION
**Pull request by kishorekumar-anchala**
# Description

This PR ensures that Azure CLI ('az') is installed and operational by attempting to retrieve its help information. If the command fails, it provides an error message and exits with a non-zero status, signaling a failure in Azure CLI availability.

#### Related issue:
[10110](https://github.com/actions/runner-images/issues/10110)

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by ijunaidm — APPROVED** [review]

**Comment by erik-bershel** [comment]
Hey @kishorekumar-anchala!
Take a look on the issue log. It's a bit more complicate than just one-time execution I suppose. With this realisation changes will never reach a runner because of a user profile deletion:
- https://github.com/actions/runner-images/pull/8294
- https://github.com/actions/runner-images/pull/8441
- https://github.com/actions/runner-images/issues/8442

**Review by ijunaidm — APPROVED** [review]

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala 

Will this work? - It is an exact port of "images/windows/scripts/build/Install-AzureCli.ps1"

```
#!/bin/bash -e
################################################################################
##  File:  install-azure-cli.sh
##  Desc:  Install Azure CLI (az)
################################################################################

# Source the helpers for use with the script
source $HELPER_SCRIPTS/etc-environment.sh

export AZURE_CONFIG_DIR="/opt/az-config"
mkdir $AZURE_CONFIG_DIR
set_etc_environment_variable "AZURE_CONFIG_DIR" $AZURE_CONFIG_DIR

export AZURE_EXTENSION_DIR="/opt/az-extensions"
mkdir $AZURE_EXTENSION_DIR
set_etc_environment_variable "AZURE_EXTENSION_DIR" $AZURE_EXTENSION_DIR

# Install Azure CLI (instructions taken from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
curl -fsSL https://aka.ms/InstallAzureCLIDeb | sudo bash

echo "azure-cli https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt" >> $HELPER_SCRIPTS/apt-sources.txt

rm -f /etc/apt/sources.list.d/azure-cli.list
rm -f /etc/apt/sources.list.d/azure-cli.list.save

echo "Warmup 'az'"
az --help > /dev/null
if [ $? -ne 0 ]; then
    echo "Command 'az --help' failed"
    exit 1
fi

invoke_tests "CLI.Tools" "Azure CLI"
```

**Pull request merged**
