### PR TITLE
[Windows] Uses the correct env var on windows

### PR DESCRIPTION
**Pull request by jessehouwing**
Based on the changes made to speed up az on ubuntu, we found that this is the correct env var to use.

# Description
New tool, Bug fixing, or Improvement?
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
**For new tools, please provide total size and installation time.**

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by jessehouwing** [comment]
Tried building the image, but it fails installing Visual Studio 2022, which was untouched by my changes:

```
    azure-arm.image: Downloading package from: https://aka.ms/vs/17/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
    azure-arm.image: Package downloaded successfully in 0.45 seconds
    azure-arm.image: Signature thumbprint do not match expected.
```

**Comment by vpolikarpov-akvelon** [comment]
> Tried building the image, but it fails installing Visual Studio 2022, which was untouched by my changes:

It happens sometimes because we pin signature thumbprint but download the newest version. This helps us to track new releases while following requirements from the security team. We will fix this soon. Thank you for letting us know.

By the way, could you please update PR description according to the predefined template?

**Review by vpolikarpov-akvelon — APPROVED** [review]

**Comment by jessehouwing** [comment]
@mikhailkoliada 👍

**Review by mikhailkoliada — APPROVED** [review]

**Pull request merged**
