### PR TITLE
[macOS] Add xcode-14.2

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description

Add xcode-14.2

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by maxim-lobanov — APPROVED** [review]

**Comment by bdrelling** [comment]
@maxim-lobanov your step does not work for `14.2` on `macos-12`, but you approved these changes so I'm assuming you helped test it. Do you happen to have further information on why it wouldn't be working? 

We're not getting a reply on #6762.

**Comment by maxim-lobanov** [comment]
@bdrelling , The PR was merged and new image with this update is not deployed yet.
It can take some time to deploy the new image everywhere.
The deployment from https://github.com/actions/runner-images/pull/6762 was reverted due to some issues. So we have to wait for next deployment.
cc: @mikhailkoliada to share timeline for new image to be available.

**Pull request merged**
