### PR TITLE
[Ubuntu] Fix heroku installation

### PR DESCRIPTION
**Pull request by Alexey-Ayupov**
# Description
Fix heroku installation

#### Related issue:
https://github.com/actions/runner-images/issues/9716

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by fardarter** [comment]
@Alexey-Ayupov Thanks for fixing this. 

Any idea what the prospective time to merge is -- I'm not aware what kinds of processes this repo follows? It's breaking my build out of the github runners packer build.

**Review by mikhailkoliada — APPROVED** [review]

**Pull request merged**
