### PR TITLE
[Windows] Update Postgres to latest v14 version

### PR DESCRIPTION
**Pull request by kishorekumar-anchala**
# Description

This PR will update the Postgres version to the latest v14 version on windows images. 

#### Related issue:
[10871](https://github.com/actions/runner-images/issues/10871)

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by lawrencegripper** [comment]
I'd been looking at this issue and there where 2 blockers, 

- vc_redist
- breaking permissions issue in installer

my current work in progress is here:

- https://github.com/actions/runner-images/pull/11047#discussion_r1869534410

**Comment by fukinbubba** [comment]
Ok

**Review by fukinbubba — COMMENTED** [review]
Ok

**Comment by kishorekumar-anchala** [comment]
it will take care under https://github.com/actions/runner-images/pull/11047

**Pull request closed without merging**
