### PR TITLE
[Ubuntu] fix README for 20.04

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by ddobranic — APPROVED** [review]

**Comment by cnry1** [comment]
是的撒多

**Comment by cnry1** [comment]
收费的方式

**Comment by cnry1** [comment]
111111

**Comment by cnry1** [comment]
12121212

**Pull request merged**
