### PR TITLE
[Windows] Update EdgeDriver signature

### PR DESCRIPTION
**Pull request by Alexey-Ayupov**
# Description
Update EdgeDriver signature

#### Related issue:
https://github.com/actions/runner-images/issues/11236

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by dav3yblaz3** [comment]
let us get this changed for test

**Review by dav3yblaz3 — COMMENTED** [review]
this looks like it could solve some issues

**Comment by dav3yblaz3** [comment]
need to try for test

**Review by shamil-mubarakshin — APPROVED** [review]

**Review by dav3yblaz3 — COMMENTED** [review]
thank you team we will try this

**Review by dav3yblaz3 — COMMENTED** [review]
looks good for test

**Comment by Hanymato** [comment]
[]()

**Comment by Hanymato** [comment]
> let us get this changed for test

**Pull request merged**
