### PR TITLE
[Ubuntu] Cleanup ubuntu 18.04 image references

### PR DESCRIPTION
**Pull request by shamil-mubarakshin**
# Description
Ubuntu 18.04 image has been deprecated and disabled. Code cleanup is required.

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by mikhailkoliada — APPROVED** [review]

**Comment by Catuchijr** [comment]
- [ ] example file altered incorect person please amend and note john do is ficticious character passing as HE identity swap for ?? financials are not a concern only my persona matter 
IMG_0512

**Pull request merged**
