### PR TITLE
[Windows] pin zstd to v1.5.5

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by slang25** [comment]
I presume this is because of this:
https://github.com/facebook/zstd/issues/3993

**Review by maxim-lobanov — APPROVED** [review]

**Comment by viceice** [comment]
issue is fixed, can be reverted 🙃

**Pull request merged**
