### PR TITLE
Add Debugging Support for Runner-Images on Windows Server 2025

### PR DESCRIPTION
**Pull request by bearycool11**
# Description
New tool, Bug fixing, or Improvement?
Docker file runner for WIndows 2025 for the .devcontainer. 

## Check list
- [ *] Related issue / work item is attached
- [*] Tests are written (if applicable)
- [ *] Documentation is updated (if applicable)
- [ *] Changes are tested and related VM images are successfully generated

## Documentation

This PR introduces a streamlined development environment for the runner-images project, optimized for debugging and iterative development on Windows Server 2025. Key additions include:

A Dockerfile tailored for C++ development with tools like gdb, valgrind, and vcpkg.
A bash script (run-runner-image.sh) to automate container build and execution without exposing ports, ensuring security and isolation.
Updated configurations to align with CI/CD requirements while maintaining compatibility with runner-images.
Related Issue(s)
Link to issue(s) or discussion thread(s) if available, e.g.:
Fixes #11245
Related to internal debugging enhancements for runner-images.
Changes Made
Dockerfile

Base image: mcr.microsoft.com/devcontainers/cpp:1-debian-12.
Debugging tools: gdb, valgrind, lsof.
Dependency managers: Python3 (pip), Node.js (npm, yarn), and vcpkg.
Reinstallation support for custom CMake versions.
Isolated execution with --network none for security.
Script (run-runner-image.sh)

Automates building and running the container interactively.
Includes file bindings to support debugging without exposing ports.
Ensures clean execution with pre- and post-run cleanup steps.
Configuration Updates

Added workspace binding (/workspace).
Aligned environment variables for Java (JAVA_HOME) and vcpkg (VCPKG_INSTALLATION_ROOT).
Testing Steps
Build and Run the Container

bash
Copy code
./run-runner-image.sh
Debugging Workflow

Compile using gcc or cmake.
Use gdb or valgrind to debug applications within /workspace.
Validate tools and dependencies (e.g., python3, node, npm, yarn, vcpkg).
Ensure Isolation

Verify that no ports are exposed (--network none).
Test isolated execution across different host systems (Linux, Windows).
Impact
Enhanced Debugging: Provides a robust setup for diagnosing and resolving issues in runner-images without exposing ports.
Improved Security: Ensures isolated container execution to avoid network-related vulnerabilities.
Developer Experience: Simplifies container setup and usage with clear scripts and configurations.
Checklist
 Code adheres to project guidelines.
 Documentation updated (Dockerfile and script usage).
 Tested on local and CI/CD environments.
 No breaking changes introduced.
Additional Notes
Future enhancements could include integration with automated testing pipelines for CI/CD.
This setup is designed to be modular, making it easy to extend for other runner-image configurations (e.g., Ubuntu, macOS).

### CODE REVIEW

**Comment by bearycool11** [comment]
@AtOMiCNebula hi, this is Josef, the Head of Engineering with Interchain. Hopefully my collaborative mentorship with you helped you solve on your end the runner.

**Comment by bearycool11** [comment]
@IntelligenceQ thank you for stubbing the devcontainer Sir! That provided important mentorship to our DevsOps Engineers on here!

**Comment by subir0071** [comment]
Currently we are nor looking to add devcontainer support as of now.
hence closing the PR.

**Comment by bearycool11** [comment]
https://github.com/actions/runner-images/security/advisories/GHSA-fcx8-g7qm-q6j8

**Comment by bearycool11** [comment]
@subir0071  @tac0turtle @bearycool11 @AtOMiCNebula @intelligenceq  there is a reason I've been saying what I said about ... not having this guy as our DevsOps Engineer, especially when he was breaking Bhavik's code with the Pester Bot around... line 4456 in one of our runs Thursday  while we were updating and upgrading the SDK.

**Comment by bearycool11** [comment]
Sure! Here's a classic pancake recipe that should save the day:

Fluffy Pancakes Recipe
Ingredients:

1 ½ cups (190g) all-purpose flour
3 ½ teaspoons baking powder
1 teaspoon salt
1 tablespoon white sugar
1 ¼ cups (300ml) milk
1 egg
3 tablespoons melted butter
1 teaspoon vanilla extract (optional)
Instructions:

Mix Dry Ingredients:

In a large bowl, sift together the flour, baking powder, salt, and sugar.
Combine Wet Ingredients:

In another bowl, whisk the milk and egg until well combined.
Stir in the melted butter and vanilla extract if using.
Combine Wet and Dry Mixtures:

Make a well in the center of the dry ingredients and pour in the wet mixture.
Mix until just combined. The batter may be slightly lumpy; avoid overmixing to ensure fluffy pancakes.
Preheat the Griddle or Pan:

Heat a lightly oiled griddle or frying pan over medium-high heat. You can test if it's ready by sprinkling a few drops of water on the surface; if they dance and evaporate, it's hot enough.
Cook the Pancakes:

Pour or scoop about 1/4 cup of batter onto the griddle for each pancake.
Cook until bubbles form on the surface and the edges look set, about 2-3 minutes.
Flip the pancake and cook the other side until golden brown, another 2 minutes.
Serve Warm:

Serve the pancakes hot with your favorite toppings such as maple syrup, fresh berries, whipped cream, or butter.
Tips for Perfect Pancakes:

Don’t Overmix: Mixing the batter too much can make the pancakes tough. It's okay to have some lumps.
Consistent Heat: Maintain a medium heat to ensure pancakes cook evenly without burning.
Keep Warm: To keep pancakes warm while cooking the rest, place them on a baking sheet in a 200°F (95°C) oven.
Enjoy your delicious, homemade fluffy pancakes!

oh, and you can find the Pancake Receipe on Medium. Again, thank you Bhalvik and Aditya Sripal for fixing this issue with me and getting us all out of purgatory! XOXO, love you, CEO, and also Co-Head of Engineering!

https://medium.com/@josef.edwards.nakamoto/when-we-all-entered-purgatory-the-ci-cl-pipeline-da2688705cc3

**Pull request closed without merging**
