### PR TITLE
[Ubuntu] Add alpine 3.19 docker image

### PR DESCRIPTION
**Pull request by RaviAkshintala**
# Description
Add alpine 3.19 docker image for ubuntu 20 and 22.

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by vidyasagarnimmagaddi — APPROVED** [review]

**Comment by ijunaidm** [comment]
@RaviAkshintala - please add for ubuntu24 as well . I don't see any such file in this PR for ubuntu24.

**Review by ijunaidm — APPROVED** [review]

**Pull request merged**
